name: GameCI Template

on: push
  
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE}}
  
jobs:
  checkLicense:
    name: Check for the Unity License
    runs-on: windows-latest
    steps:
      - name: Fail - No license
        if: ${{ !startsWith(env.UNITY_LICENSE, '<') }}
        run: exit 1
  